/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ooieueioo_potestjni_PoJNITtest */

#ifndef _Included_com_ooieueioo_potestjni_PoJNITtest
#define _Included_com_ooieueioo_potestjni_PoJNITtest
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class: om_ooieueioo_potestjni_PoJNITtest
 * Method: WriteProc, Java send String to C, then C return string, can write parameter to /proc/eth0
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_ooieueioo_potestjni_PoJNITtest_WriteProc(JNIEnv *, jclass, jstring, jstring);

/***** Po area
 *
*/
JNIEXPORT jstring JNICALL Java_com_ooieueioo_potestjni_PoJNITtest_ReadMacAddress(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
