/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ooieuioo_potestjni_PoJNITtest */

#ifndef _Included_com_imobile_iq8readserialnumber_iMobileReadSerialNumber
#define _Included_com_imobile_iq8readserialnumber_iMobileReadSerialNumber
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Class: com_imobile_iq8readserialnumber_iMobileReadSerialNumber
 * Method: ReadSN
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_imobile_iq8readserialnumber_iMobileReadSerialNumber_ReadSN(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
