/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ooieueioo_pojnireadwriteproc_PoJNIT */

#ifndef _Included_com_ooieueioo_pojnireadwriteproc_PoJNIT
#define _Included_com_ooieueioo_pojnireadwriteproc_PoJNIT
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class: com_ooieueioo_pojnireadwriteproc_PoJNIT
 * Method: ReadProc, Java send String to C, then C return string
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_ooieueioo_pojnireadwriteproc_PoJNIT_ReadProc(JNIEnv *, jclass, jstring);

/**
 * Class: com_ooieueioo_pojnireadwriteproc_PoJNIT
 * Method: WriteProc, Java send String to C, then C return string, can write parameter to /proc/Po_value
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_ooieueioo_pojnireadwriteproc_PoJNIT_WriteProc(JNIEnv *, jclass, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
